### PR TITLE
Raven-hydro v3.5 + support on Windows

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@julemai 

This PR adds the newest Raven release (v3.5) directly from the raven project webpage. Please feel free to make any changes that may be needed. This also add Windows support! If you're familiar with building using cmake, feel free to give this a look. Thanks!

**Comment by julemai** [comment]
Not sure how sustainable [recipe/CMakeLists.txt](https://github.com/conda-forge/raven-hydro-feedstock/pull/5#diff-067becd4c878c9ed8da8911c8f12eb66d012248546a89512aa34812bfeae28b8) is with the grouping of codes (i.e., one would need to keep this updated when new modules are added to Raven in later versions). 

I would have probably left the option of integrating unreleased versions (from my website) but I guess everything you need for PAVICS is now in a released version. You would just need to roll back to the previous version of [recipe/meta.yaml](https://github.com/conda-forge/raven-hydro-feedstock/pull/5#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a) when you want new features and don't want to wait for a release.

The rest looks good to me.

**Comment by Zeitsperre** [comment]
@julemai I completely agree with the comment about CMake. The challenge here is that the Windows-based devs don't use command-based approaches to building the binaries. If we could figure out how to configure the equivalent commands for building with the Windows MSVC compiler in MinGW64 (ie: `cl.exe {flags} {targets}`), this would solve all issues. 

I could leave the code for grabbing your internal beta buils as comments in the recipe if that helps. We can use the same naming mechanism as the release archives to make things simpler as well. If it's still useful, we can keep it!

**Comment by julemai** [comment]
@Zeitsperre I totally understand your problem with CMake and I'm sorry I can't help with that. :(

I guess having the backup option commented out, might be helpful in case we need a non-released version later again. I agree that the "final" version of this should always grab the code from the Raven website.

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
FYI @huard

**Comment by Zeitsperre** [comment]
@julemai I'm going to go forward with merging this since it's working, despite the complex build configuration to support Windows users. Ostrich is still a major hurdle due to the development configuration on Windows. Hopefully we can find some time to work on that.

**Pull request merged**
