### PR TITLE
Add build variants for libnetcdf

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

PVI @tlvu

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@conda-forge/help-python

I need to be able to offer this package built against libnetcdf 4.8.1 and 4.9.x. How do I properly configure that here?

My workaround was to manually add `libnetcdf` 4.8.1 as a build variant here, since all the documented approaches (using `conda_build_config.yaml`) were not working.  This is a hideous approach to fixing the problem, and I'd rather do this properly.

**Review by huard — APPROVED** [review]

**Pull request merged**
