### PR TITLE
Fix Raven v3.6 Package

### LINKED ISSUE #7: Raven-hydro v3.6 is failing to build
### Comment:

It appears that the source code for v3.6 is significantly different from v3.5, enough so that the patching and compiling is failing for us. We'll need to open a patch PR to get this working.

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #7

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@julemai

Do you know what this `MFUSGLib` target is? I don't see the files for it in the source code for Raven-Hydro. If it's unimportant or remnants of a different executable, would it be possible to either:
- Add these missing files to the zip file hosted on the Raven website?
- Remove the target in the CMakeLists.txt in the Raven-v3.6 zip file, or patch it out of the list here?

Compiling FORTRAN code using Visual Studio on conda-forge is not as intuitive as it is for C/C++. If it's very important, I might need your/James's help with this task.

**Comment by julemai** [comment]
@Zeitsperre, the `Makefile` works perfectly fine. I just downloaded the code and run `make` without any issue (had to remove the `-c++11` in line 20 because my compiler does not need that flag). There is no Fortran code in Raven. I do not use Visual Studio to compile anything. Those files are all coming from James. He might have tested something with some Fortran code. Just ignore all the visual studio files. The `MFUSGLib ` is not required at all. :)

**Comment by Zeitsperre** [comment]
Hey @julemai, thanks for the lightning-fast response!

Alright, I'm going to patch it out of the CMakeLists.txt then. The compiler for Windows builds on Conda requires CMake, so I need to have a clean/valid CMakeLists.txt for everything to compile properly. The Mac/Linux builds are perfectly fine at least.

**Comment by julemai** [comment]
Yeah, maybe double-check with James. But I think it is just some coupling with a groundwater model which should not be too important for our applications here.

**Pull request merged**
